config/routes.rb
Webservices::Application.routes.draw do
  resources :dictionaries
  # resources :dictionaries, :collection => { :recent => :get }, :member => { :modify => :put }
  #resources :dictionaries,  :collection => { :recent => :get }, :member     => { :modify => :put }
  # get    "/search",  to: 'dictionaries#search',       as: 'search'
  get    "/autocomplete",  to: 'dictionaries#autocomplete',       as: 'autocomplete'
  # match 'search', to: 'dictionaries#search', via: [:get, :post]

  root :to => "dictionaries#index"
end

app/models/dictionary.rb
class Dictionary < ActiveRecord::Base
  # searchkick
  searchkick autocomplete: ['term'], text_start: ['term'], suggest: ["term"]


  def search_data
    as_json only: [:term, :definition, :created_at]
    {
      term: term,
      definition: definition,
      created_at: created_at
    }
  end

  def self.search_query(param, page)
    Dictionary.search "%#{param}%", suggest: true, misspellings: {distance: 2}, page: page, per_page: 10, suggest: true
  end

  def self.search_autocomplete(param)
    Dictionary.search(param, fields: [{term: :text_start}], limit: 15).map(&:term)
  end
  # Dictionary.reindex

  # def self.search(param)
  #   # Dictionary.where(:first, :conditions => ['lower(term) LIKE ?', "%#{param.downcase}%"])
  #   # Dictionary.where('lower(term) LIKE ?', "%#{param.downcase}%").order(:term)
  #   # Dictionary.search("%#{param.downcase}%", where: {in_stock: true}, limit: 10, offset: 50)
  #   Dictionary.search("%#{param}%")
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController
  before_filter :authorize
  before_action :set_dictionary, only: [:show, :edit, :update, :destroy]

  respond_to :html, :xml, :json, :js

  # GET /dictionaries
  def index
    if params[:query].present?
      @dictionaries = Dictionary.search_query(params[:query], params[:page])
    else
      @dictionaries = Dictionary.order(:term).paginate(page: params[:page],:per_page=> 10)
    end
    respond_with @dictionaries

    # respond_to do |format|
    #   format.html
    #   format.json { render json: @dictionaries }
    #   format.xml  { render xml: @dictionaries }
    # end
  end

  def autocomplete
    render json: Dictionary.search_autocomplete(params[:query])
    # render json: Dictionary.search(params[:query], autocomplete: true, fields: [{term: :text_start}], limit: 15).map(&:term)
  end

  # GET /dictionaries/1
  def show
  end

  # GET /dictionaries/new
  def new
    respond_with @dictionary = Dictionary.new
  end

  # GET /dictionaries/1/edit
  def edit
  end

  # POST /dictionaries
  def create
    @dictionary = Dictionary.new(dictionary_params)

    flash[:notice] = 'Dictionary was successfully created.' if @dictionary.save
    respond_with @dictionary
  end

  # PATCH/PUT /dictionaries/1
  def update
    if @dictionary.update(dictionary_params)
      respond_with @dictionary, notice: 'Dictionary was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /dictionaries/1
  def destroy
    @dictionary.destroy
    redirect_to dictionaries_url, notice: 'Dictionary was successfully destroyed.'
  end

  def recent
    render text: 'recent'
  end

  def modify
    render text: 'modify'
  end

  protected
    def authorize
      authenticate_or_request_with_http_basic do |username, password|
        username == 'admin' && password == 'secret'
      end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dictionary
      @dictionary = Dictionary.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def dictionary_params
      params.require(:dictionary).permit(:term, :definition)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%= value %></div>
  <% end -%>
</div>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/dictionaries/_dictionary.html.erb
<tr>
  <td>
    <dl>
      <dt><%= link_to dictionary.term, dictionary_path(dictionary)%> <%= link_to edit_dictionary_path(dictionary) do %> <i class="fa fa-pencil fa-fw"></i> <% end %></dt>
      <dd><%= dictionary.definition %></dd>
    </dl>
  </td>
  <td class='actions'>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")), dictionary_path(dictionary), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger' %>
  </td>
</tr>

app/views/dictionaries/_form.html.erb
<%= simple_form_for @dictionary, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :term %>
  <%= f.input :definition %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                dictionaries_path, :class => 'btn' %>
  </div>
<% end %>

app/views/dictionaries/edit.html.erb
<%- model_class = Dictionary -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/dictionaries/index.html.erb
<%- model_class = Dictionary -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= render :partial => 'shared/search_form' %>
<%= will_paginate @dictionaries %>
<%- model_class = Dictionary -%>
<div id="dictionaries">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:term) %> & <%= model_class.human_attribute_name(:definition) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
       <%= render @dictionaries %>
      </tr>
    </tbody>
  </table>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
new_dictionary_path,
:class => 'btn btn-primary' %>

app/views/dictionaries/index.js.erb
$("#dictionaries").html("<%= escape_javascript(render(@dictionaries))%>");

app/views/dictionaries/new.html.erb
<%- model_class = Dictionary -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/dictionaries/show.html.erb
<%- model_class = Dictionary -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:term) %>:</strong></dt>
  <dd><%= @dictionary.term %></dd>
  <dt><strong><%= model_class.human_attribute_name(:definition) %>:</strong></dt>
  <dd><%= @dictionary.definition %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              dictionaries_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_dictionary_path(@dictionary), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              dictionary_path(@dictionary),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Webservices" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.9.3/typeahead.min.js" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Webservices</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/shared/_search_form.html.erb
<%= form_tag dictionaries_path, method: :get, remote: true do %>
  <div class="input-append">
      <%= text_field_tag :query, params[:query], placeholder: 'Enter search term...', id: "query", autocomplete: "off", name: "query"%>
    <button type="submit" class="btn search-query">
      <i class="icon-search"></i>
    </button>
  </div>
<% end %>

<a href="#" data-background-color="#990000">Paint it red</a>


<script>
  $("#query").typeahead({
    name: "query",
    remote: "/autocomplete?query=%QUERY"
  });
</script>